version: '3'
services:
  client:
    environment:
      - REACT_APP_API_URL=http://server:3001
    restart: unless-stopped

  server:
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  db:
    restart: unless-stopped 